version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - 8080:80
    volumes:
      - .:/srv/app
    links:
      - postgres
    environment:
      DB_HOST: postgres
      DB_DATABASE: laravel_docker
      DB_USERNAME: postgres
      DB_PASSWORD: postgres

  postgres:
    image: postgres:9.5
    restart: always
    volumes:
      - "./.data/db:/var/lib/postgresql"
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres